name: 'Fastapi Performance tuning measurements'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 300
    strategy:
      matrix:
        os: [ ubuntu-latest ] # , macos-latest, windows-latest
        python-version: [ '3.10' ] # '3.6', '3.7', '3.8', '3.9', 
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Docker Compose'
        uses: isbang/compose-action@v1.3.2
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build --force-recreate"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f test_files/requirements.txt ]; then pip install -r test_files/requirements.txt; fi
          mkdir -p reports
          docker-compose ps --all
      - name: 'Measure middlewares'
        timeout-minutes: 30
        run: |
          pytest -x --html=./reports/middlewares_pytest.html --self-contained-html --show-capture=stdout -vv -rP test_files/ -m middlewares
      - name: 'Measure json response classes'
        timeout-minutes: 30
        run: |
          curl -v http://127.0.0.1:8006/sync/big_json_response/
          curl -v http://127.0.0.1:8007/sync/big_json_response/
          curl -v http://127.0.0.1:8008/sync/big_json_response/
          pytest -x --html=./reports/json_classes_pytest.html --self-contained-html --show-capture=stdout -vv -rP test_files/ -m json_classes
      - name: 'Measure sync vs async endpoints'
        timeout-minutes: 30
        run: |
          pytest -x --html=./reports/sync_async_pytest.html --self-contained-html --show-capture=stdout -vv -rP test_files/ -m sync_async
      - uses: actions/upload-artifact@v2
        with:
          name: Pytest-Report-${{ matrix.python-version }}
          path: ./reports
