name: 'Fastapi Performance tuning measurements'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ] # , macos-latest, windows-latest
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Docker Compose'
        uses: isbang/compose-action@v1.3.2
        with:
          compose-file: "./docker/docker-compose.yml"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f test_files/requirements.txt ]; then pip install -r test_filtes/requirements.txt; fi
      - name: 'Run Measurements'
        run: |
          pytest  -x --html=pytest.html --self-contained-html --show-capture=stdout -vv -rP test_files/
      - uses: actions/upload-artifact@v2
        with:
          name: Pytest-Report-${{ matrix.python-version }}
          path: pytest.html
