name: Update branch

on:
  pull_request
 
permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge on dependabot PRs
        uses: daneden/enable-automerge-action@v1
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          # Allowed values: MERGE | SQUASH | REBASE
          # Defaults to MERGE
          merge-method: MERGE
      - name: "Update PR Branch"
        uses: adRise/update-pr-branch@v0.7.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          base: 'main'
          required_approval_count: 0
          require_passed_checks: false
          sort: 'created'
          direction: 'desc'
          require_auto_merge_enabled: true
