name: Update branch

on:
  push:
    branches:
      - 'main'

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: "Update PR Branch"
        uses: adRise/update-pr-branch@v0.7.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          base: 'main'
          required_approval_count: 0
          require_passed_checks: false
          sort: 'created'
          direction: 'desc'
